CREATE DATABASE HOTElll
USE HOTElll
CREATE TABLE ROOMTYPESBYOCCUPANCY(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR (50),
)
INSERT INTO ROOMTYPESBYOCCUPANCY
VALUES('SINGLE')
INSERT INTO ROOMTYPESBYOCCUPANCY
VALUES('DOUBLE')
INSERT INTO ROOMTYPESBYOCCUPANCY
VALUES('MULTI')

CREATE TABLE ROOMTYPESBYLAYOUT(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR (50),
)
INSERT INTO ROOMTYPESBYLAYOUT
VALUES('STANDARD')
INSERT INTO ROOMTYPESBYLAYOUT
VALUES('DELUXE')
INSERT INTO ROOMTYPESBYLAYOUT
VALUES('JOINT')
INSERT INTO ROOMTYPESBYLAYOUT
VALUES('CONNECTING')

CREATE TABLE ROOMS(
ID INT PRIMARY KEY IDENTITY,
ROOMTYPESBYOCCUPANCYID INT REFERENCES ROOMTYPESBYOCCUPANCY(ID),
ROOMTYPESBYLAYOUTID INT REFERENCES ROOMTYPESBYLAYOUT(ID),
ROOMNUM INT UNIQUE
)

INSERT INTO ROOMS
VALUES(2,1,101)
INSERT INTO ROOMS
VALUES(3,2,102)
INSERT INTO ROOMS
VALUES(1,4,103)

CREATE TABLE CUSTOMERS(
ID INT PRIMARY KEY IDENTITY,
SAA NVARCHAR (50),
PHONENUMBER NVARCHAR(100),
EMAIL NVARCHAR(100)
)
INSERT INTO CUSTOMERS
VALUES('NAZ MEMMEDZADEH BAHRUZ','+99450377263846','AB.A4@mail.com')
INSERT INTO CUSTOMERS
VALUES('AYDAN MEMMEDZADEH BAHRUZ','+994559972846','GTB.A5@mail.com')
INSERT INTO CUSTOMERS
VALUES('MURAD MEMMEDZADEH BAHRUZ','+994559472826','MRD.A5@mail.com')


CREATE TABLE RESERVATIONS(
ID INT PRIMARY KEY IDENTITY,
ROOMID INT REFERENCES ROOMS(ID),
CUSTOMERID INT REFERENCES CUSTOMERS(ID),
CHECKIN DATE ,
CHECKOUT DATE ,
)
INSERT INTO RESERVATIONS
VALUES (1,2,'2022-05-10','2022-05-15')
INSERT INTO RESERVATIONS
VALUES (2,3,'2022-07-11','2022-08-11')
INSERT INTO RESERVATIONS
VALUES (3,1,'2022-09-20','2022-09-22')

CREATE TABLE PAYMENTS(
ID INT PRIMARY KEY IDENTITY,
CUSTOMERID INT REFERENCES CUSTOMERS(ID),
RESERVATIONID INT REFERENCES RESERVATIONS(ID),
PAY MONEY
)
INSERT INTO PAYMENTS
VALUES (1,3,700)
INSERT INTO PAYMENTS
VALUES (3,2,900)
INSERT INTO PAYMENTS
VALUES (2,1,1000)


CREATE TABLE SPENDINGS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(100),
CUSTOMERID INT REFERENCES CUSTOMERS(ID),
PAY MONEY
)
INSERT INTO SPENDINGS
VALUES('FOOD',1,300)
INSERT INTO SPENDINGS
VALUES('POOL',2,200)
INSERT INTO SPENDINGS
VALUES('PARK',3,120)
INSERT INTO SPENDINGS
VALUES('CLUB',2,500)
INSERT INTO SPENDINGS
VALUES('SPA',3,750);
SELECT * FROM SPENDINGS

CREATE VIEW AVAILABLEROOMS
AS
SELECT ROOMS.ROOMNUM,ROOMTYPESBYLAYOUT.NAME,ROOMTYPESBYOCCUPANCY.ID FROM ROOMS
JOIN ROOMTYPESBYLAYOUT
ON
ROOMS.ROOMTYPESBYLAYOUTID=ROOMTYPESBYLAYOUT.ID
JOIN ROOMTYPESBYOCCUPANCY
ON
ROOMS.ROOMTYPESBYOCCUPANCYID=ROOMTYPESBYOCCUPANCY.ID
GROUP BY ROOMS.ROOMNUM,ROOMTYPESBYLAYOUT.NAME,ROOMTYPESBYOCCUPANCY.ID

CREATE PROCEDURE GETSPENDINGSOFCUSTOMER @customerid int
AS
SELECT CUSTOMERS.SAA,SPENDINGS.NAME,SPENDINGS.PAY FROM CUSTOMERS
JOIN SPENDINGS
ON
CUSTOMERS.ID=CUSTOMERID
WHERE CUSTOMERS.ID=@customerid
ORDER BY SPENDINGS.PAY DESC



CREATE FUNCTION GETSUMOFSPENDINGSOFCUSTS (@customerid int)
RETURNS MONEY
AS 
BEGIN
		DECLARE @sumofspendings INT
		SELECT @sumofspendings=SUM(SPENDINGS.PAY) FROM SPENDINGS 
		JOIN CUSTOMERS
		ON
		SPENDINGS.CUSTOMERID=CUSTOMERS.ID
		RETURN @sumofspendings  
END
SELECT [DBO].[GETSUMOFSPENDINGSOFCUSTS] (3)

CREATE TRIGGER DELETECUSTOMERS ON CUSTOMERS
AFTER DELETE
AS
BEGIN	
		SELECT COUNT(*) 'COUNT OF CUSTOMERS'
END
		DELETE FROM CUSTOMERS
		WHERE CUSTOMERS.ID=2
		SELECT * FROM CUSTOMERS



CREATE TRIGGER CHANGERESERVATION ON RESERVATIONS
AFTER UPDATE
AS
BEGIN	
		SELECT RESERVATIONS.CHECKIN 'UPDATED CHECK IN' ,RESERVATIONS.CHECKOUT 'UPDATED CHECK OUT' FROM RESERVATIONS
END
		UPDATE RESERVATIONS
		SET RESERVATIONS.CHECKIN='2022-09-11' 
	    UPDATE RESERVATIONS
		SET RESERVATIONS.CHECKOUT='2022-09-17' 

		WHERE RESERVATIONS.CUSTOMERID=3		